In [1]:
# from google.colab import files
import pandas as pd
import re
import unicodedata

In [6]:
uploaded = files.upload()

Saving Quy_Che_Quy_Dinh_Cleaned.csv to Quy_Che_Quy_Dinh_Cleaned.csv
Saving Thong_Tin_Trung_Tam_Cleaned.csv to Thong_Tin_Trung_Tam_Cleaned.csv

In [5]:
# df1 = pd.read_csv('Quy_Che_Quy_Dinh_Cleaned.csv')
# df2 = pd.read_csv('Thong_Tin_Khoa_Cleaned.csv')
# df3 = pd.read_csv('Thong_Tin_Trung_Tam_Cleaned.csv')
# df4 = pd.read_csv('Thong_Tin_Truong_Cleaned.csv')
# df5 = pd.read_csv('Thong_Tin_Tuyen_Sinh_Cleaned.csv')
df = pd.read_csv('data_clean.csv')

In [6]:
dict_viet_tat = {
    'sv': 'sinh viên',
    'gv': 'giảng viên',
    'đh': 'đại học',
    'cđ': 'cao đẳng',
    'tc': 'tín chỉ',
    'hk': 'học kỳ',
    'iuh': 'đại học công nghiệp thành phố hồ chí minh',
    'ktx': 'ký túc xá',
    'tp.hcm': 'thành phố hồ chí minh',
    'tphcm': 'thành phố hồ chí minh'
}

def replace_viet_tat(text):
    words = text.split()
    words = [dict_viet_tat.get(word, word) for word in words]
    return ' '.join(words)

def normalize_vietnamese_text(text):
    if not isinstance(text, str):
        return ""

    # chuẩn hóa Unicode về chuẩn NFC
    text = unicodedata.normalize('NFC', text)

    # chuyển toàn bộ thành chữ thường
    text = text.lower()

    # xử lý từ viết tắt
    text = replace_viet_tat(text)

    #xóa khoảng trắng thừa (tab, xuống dòng, khoảng trắng kép)
    text = re.sub(r'\s+', ' ', text).strip()

    #sdt
    text = re.sub(r'\b0\d{2,3}[\s.-]?\d{3,4}[\s.-]?\d{3,4}\b', '<PHONE>', text)

    # email
    text = re.sub(r'\S+@\S+', '<EMAIL>', text)

    # url
    text = re.sub(r'\b(?:https?://|www\.)\S+\b', '<URL>', text)
    text = re.sub(r'\b[A-Za-z0-9.-]+\.(vn|com|org|edu|gov|net)\b', '<URL>', text)

    return text

In [7]:
df['Normalized_Text'] = df['Cleaned_Text'].apply(normalize_vietnamese_text)
df

,STT,Thong_Tin,Label,Cleaned_Text,Normalized_Text
0,1,Website chính thức của Trung tâm Quản trị Hệ t...,Thong_Tin_Trung_Tam,website chính thức của trung tâm quản trị hệ t...,website chính thức của trung tâm quản trị hệ t...
1,2,Tên tiếng Anh của Trung tâm Quản trị Hệ thống ...,Thong_Tin_Trung_Tam,tên tiếng anh của trung tâm quản trị hệ thống ...,tên tiếng anh của trung tâm quản trị hệ thống ...
2,3,Tên viết tắt của Trung tâm Quản trị Hệ thống l...,Thong_Tin_Trung_Tam,tên viết tắt của trung tâm quản trị hệ thống l...,tên viết tắt của trung tâm quản trị hệ thống l...
3,4,Trong quá trình xây dựng và phát triển ban đầu...,Thong_Tin_Trung_Tam,trong quá trình xây dựng và phát triển ban đầu...,trong quá trình xây dựng và phát triển ban đầu...
4,5,"Tháng 8 năm 2019, Trung tâm Quản trị Hệ thống ...",Thong_Tin_Trung_Tam,"tháng 8 năm 2019, trung tâm quản trị hệ thống ...","tháng 8 năm 2019, trung tâm quản trị hệ thống ..."
...,...,...,...,...,...
5351,5352,"Hội thi tay nghề Bộ Công thương năm 2014, IUH ...",Thong_Tin_Truong,"hội thi tay nghề bộ công thương năm 2014, iuh ...","hội thi tay nghề bộ công thương năm 2014, đại ..."
5352,5353,Hoạt động kỷ niệm ngày Quốc tế Phụ nữ 8/3/2014,Thong_Tin_Truong,hoạt động kỷ niệm ngày quốc tế phụ nữ 8/3/2014,hoạt động kỷ niệm ngày quốc tế phụ nữ 8/3/2014
5353,5354,Tiến độ đào tạo năm học 2014-2015 (theo 2 học kỳ),Thong_Tin_Truong,tiến độ đào tạo năm học 2014-2015 (theo 2 học kỳ),tiến độ đào tạo năm học 2014-2015 (theo 2 học kỳ)
5354,5355,Kế hoạch thi tốt nghiệp đợt tháng 07 năm 2014,Thong_Tin_Truong,kế hoạch thi tốt nghiệp đợt tháng 07 năm 2014,kế hoạch thi tốt nghiệp đợt tháng 07 năm 2014
5355,5356,Danh sách các nhà tài trợ học bổng Sinh viên n...,Thong_Tin_Truong,danh sách các nhà tài trợ học bổng sinh viên n...,danh sách các nhà tài trợ học bổng sinh viên n...

In [19]:
df2['Normalized_Text'] = df2['Cleaned_Text'].apply(normalize_vietnamese_text)
df2

,STT,Thông tin,Label,Cleaned_Text,Normalized_Text
0,1,Website của khoa công nghệ cơ khí: fme.iuh.edu.vn,Thong_tin_khoa,Website của khoa công nghệ cơ khí: fme.iuh.edu.vn,website của khoa công nghệ cơ khí: <URL>
1,2,Email của khoa công nghệ cơ khí: fme@iuh.edu.vn,Thong_tin_khoa,Email của khoa công nghệ cơ khí: fme@iuh.edu.vn,email của khoa công nghệ cơ khí: <EMAIL>
2,3,Khoa Công nghệ Cơ khí được thành lập năm 2005....,Thong_tin_khoa,Khoa Công nghệ Cơ khí được thành lập năm 2005....,khoa công nghệ cơ khí được thành lập năm 2005....
3,4,Khoa Công nghệ Cơ khí hiện nay đảm nhiệm công ...,Thong_tin_khoa,Khoa Công nghệ Cơ khí hiện nay đảm nhiệm công ...,khoa công nghệ cơ khí hiện nay đảm nhiệm công ...
4,5,Khoa Công nghệ Cơ khí có sáu đơn vị trực thuộc...,Thong_tin_khoa,Khoa Công nghệ Cơ khí có sáu đơn vị trực thuộc...,khoa công nghệ cơ khí có sáu đơn vị trực thuộc...
...,...,...,...,...,...
1002,1003,Hội thảo khoa học sinh viên 2019,Thong_tin_khoa,Hội thảo khoa học sinh viên 2019,hội thảo khoa học sinh viên 2019
1003,1004,Thông báo về việc mở lớp học phần học lại của ...,Thong_tin_khoa,Thông báo về việc mở lớp học phần học lại của ...,thông báo về việc mở lớp học phần học lại của ...
1004,1005,Kế hoạch hội thảo sinh viên năm 2019,Thong_tin_khoa,Kế hoạch hội thảo sinh viên năm 2019,kế hoạch hội thảo sinh viên năm 2019
1005,1006,Chương trình ngày hội tư vấn và thay nhớt miễn...,Thong_tin_khoa,Chương trình ngày hội tư vấn và thay nhớt miễn...,chương trình ngày hội tư vấn và thay nhớt miễn...
1006,1007,Thông báo danh sách dự kiến sinh viên nhận học...,Thong_tin_khoa,Thông báo danh sách dự kiến sinh viên nhận học...,thông báo danh sách dự kiến sinh viên nhận học...

In [20]:
df3['Normalized_Text'] = df3['Cleaned_Text'].apply(normalize_vietnamese_text)
df3

,STT,Text,Labels,Cleaned_Text,Normalized_Text
0,1,Website chính thức của Trung tâm Quản trị Hệ t...,Thong_Tin_Trung_Tam,Website chính thức của Trung tâm Quản trị Hệ t...,website chính thức của trung tâm quản trị hệ t...
1,2,Tên tiếng Anh của Trung tâm Quản trị Hệ thống ...,Thong_Tin_Trung_Tam,Tên tiếng Anh của Trung tâm Quản trị Hệ thống ...,tên tiếng anh của trung tâm quản trị hệ thống ...
2,3,Tên viết tắt của Trung tâm Quản trị Hệ thống l...,Thong_Tin_Trung_Tam,Tên viết tắt của Trung tâm Quản trị Hệ thống l...,tên viết tắt của trung tâm quản trị hệ thống l...
3,4,Trong quá trình xây dựng và phát triển ban đầu...,Thong_Tin_Trung_Tam,Trong quá trình xây dựng và phát triển ban đầu...,trong quá trình xây dựng và phát triển ban đầu...
4,5,"Tháng 8 năm 2019, Trung tâm Quản trị Hệ thống ...",Thong_Tin_Trung_Tam,"Tháng 8 năm 2019, Trung tâm Quản trị Hệ thống ...","tháng 8 năm 2019, trung tâm quản trị hệ thống ..."
...,...,...,...,...,...
1213,1214,"Để phù hợp với môi trường thao trường, hệ thốn...",Thong_Tin_Trung_Tam,"Để phù hợp với môi trường thao trường, hệ thốn...","để phù hợp với môi trường thao trường, hệ thốn..."
1214,1215,Thiết bị tính điểm bia bắn do Trung tâm R&DTec...,Thong_Tin_Trung_Tam,Thiết bị tính điểm bia bắn do Trung tâm RDTech...,thiết bị tính điểm bia bắn do trung tâm rdtech...
1215,1216,"Dự án ""Hệ thống thông minh tính điểm tự động c...",Thong_Tin_Trung_Tam,Dự án Hệ thống thông minh tính điểm tự động ch...,dự án hệ thống thông minh tính điểm tự động ch...
1216,1217,"Về mặt phần cứng, hệ thống của Trung tâm R&DTe...",Thong_Tin_Trung_Tam,"Về mặt phần cứng, hệ thống của Trung tâm RDTec...","về mặt phần cứng, hệ thống của trung tâm rdtec..."
1217,1218,Phần mềm hệ thống tính điểm của Trung tâm R&DT...,Thong_Tin_Trung_Tam,Phần mềm hệ thống tính điểm của Trung tâm RDTe...,phần mềm hệ thống tính điểm của trung tâm rdte...

In [21]:
df4['Normalized_Text'] = df4['Cleaned_Text'].apply(normalize_vietnamese_text)
df4

,STT,Content,Label,Cleaned_Text,Normalized_Text
0,1,Chúc mừng Giáng sinh và Chúc mừng năm mới 2026,Thong_Tin_Truong,Chúc mừng Giáng sinh và Chúc mừng năm mới 2026,chúc mừng giáng sinh và chúc mừng năm mới 2026
1,2,Hội Cựu chiến binh IUH về nguồn kỷ niệm 81 năm...,Thong_Tin_Truong,Hội Cựu chiến binh IUH về nguồn kỷ niệm 81 năm...,hội cựu chiến binh đại học công nghiệp thành p...
2,3,Đại biểu IUH trúng cử vào Ban Thường vụ Công đ...,Thong_Tin_Truong,Đại biểu IUH trúng cử vào Ban Thường vụ Công đ...,đại biểu đại học công nghiệp thành phố hồ chí ...
3,4,Biến vảy cá thành giá trị xanh: Sinh viên IUH ...,Thong_Tin_Truong,Biến vảy cá thành giá trị xanh: Sinh viên IUH ...,biến vảy cá thành giá trị xanh: sinh viên đại ...
4,5,"Vượt qua hơn 140 đội thi, sinh viên IUH giành ...",Thong_Tin_Truong,"Vượt qua hơn 140 đội thi, sinh viên IUH giành ...","vượt qua hơn 140 đội thi, sinh viên đại học cô..."
...,...,...,...,...,...
538,539,Cơ chế hoạt động tự chủ thí điểm của Trường Đạ...,Thong_Tin_Truong,Cơ chế hoạt động tự chủ thí điểm của Trường Đạ...,cơ chế hoạt động tự chủ thí điểm của trường đạ...
539,540,"Hiện nay, Trường Đại học Công nghiệp TP.HCM đư...",Thong_Tin_Truong,"Hiện nay, Trường Đại học Công nghiệp TP.HCM đư...","hiện nay, trường đại học công nghiệp thành phố..."
540,541,Hỏi: Trường Đại học Công nghiệp TP.HCM (IUH) đ...,Thong_Tin_Truong,Hỏi: Trường Đại học Công nghiệp TP.HCM (IUH) đ...,hỏi: trường đại học công nghiệp thành phố hồ c...
541,542,Hỏi: Các tên gọi cũ của Đại học Công nghiệp TP...,Thong_Tin_Truong,Hỏi: Các tên gọi cũ của Đại học Công nghiệp TP...,hỏi: các tên gọi cũ của đại học công nghiệp th...
542,543,Hỏi: Sự kiện nào diễn ra vào năm 1994 đối với ...,Thong_Tin_Truong,Hỏi: Sự kiện nào diễn ra vào năm 1994 đối với ...,hỏi: sự kiện nào diễn ra vào năm 1994 đối với ...

In [22]:
df5['Normalized_Text'] = df5['Cleaned_Text'].apply(normalize_vietnamese_text)
df5

,STT,Text,Labels,Cleaned_Text,Normalized_Text
0,1,"Năm 2026, Trường Đại học Công nghiệp Thành phố...",Thong_Tin_Tuyen_Sinh,"Năm 2026, Trường Đại học Công nghiệp Thành phố...","năm 2026, trường đại học công nghiệp thành phố..."
1,2,Nguyên tắc chung trong công tác tuyển sinh đại...,Thong_Tin_Tuyen_Sinh,Nguyên tắc chung trong công tác tuyển sinh đại...,nguyên tắc chung trong công tác tuyển sinh đại...
2,3,Đối tượng tuyển sinh hệ đại học chính quy năm ...,Thong_Tin_Tuyen_Sinh,Đối tượng tuyển sinh hệ đại học chính quy năm ...,đối tượng tuyển sinh hệ đại học chính quy năm ...
3,4,Thí sinh dự tuyển vào Trường Đại học Công nghi...,Thong_Tin_Tuyen_Sinh,Thí sinh dự tuyển vào Trường Đại học Công nghi...,thí sinh dự tuyển vào trường đại học công nghi...
4,5,Phạm vi tuyển sinh đại học hệ chính quy năm 20...,Thong_Tin_Tuyen_Sinh,Phạm vi tuyển sinh đại học hệ chính quy năm 20...,phạm vi tuyển sinh đại học hệ chính quy năm 20...
...,...,...,...,...,...
1081,1082,Trong khoảng thời gian 01 tháng chờ đợi làm th...,Thong_Tin_Tuyen_Sinh,Trong khoảng thời gian 01 tháng chờ đợi làm th...,trong khoảng thời gian 01 tháng chờ đợi làm th...
1082,1083,Học viên cao học tại IUH tốt nghiệp loại xuất ...,Thong_Tin_Tuyen_Sinh,Học viên cao học tại IUH tốt nghiệp loại xuất ...,học viên cao học tại đại học công nghiệp thành...
1083,1084,IUH cho phép học viên thạc sĩ tham gia trao đổ...,Thong_Tin_Tuyen_Sinh,IUH cho phép học viên thạc sĩ tham gia trao đổ...,đại học công nghiệp thành phố hồ chí minh cho ...
1084,1085,"Ngoài IELTS và VSTEP, các chứng chỉ ngoại ngữ ...",Thong_Tin_Tuyen_Sinh,"Ngoài IELTS và VSTEP, các chứng chỉ ngoại ngữ ...","ngoài ielts và vstep, các chứng chỉ ngoại ngữ ..."
1085,1086,"Trong trường hợp thiên tai, dịch bệnh bất khả ...",Thong_Tin_Tuyen_Sinh,"Trong trường hợp thiên tai, dịch bệnh bất khả ...","trong trường hợp thiên tai, dịch bệnh bất khả ..."

In [11]:
df1_final = df[['STT', 'Cleaned_Text', 'Label', 'Normalized_Text']]

print(f'df1_final shape: {df1_final.shape}')
display(df1_final)

df1_final shape: (5356, 4)

,STT,Cleaned_Text,Label,Normalized_Text
0,1,website chính thức của trung tâm quản trị hệ t...,Thong_Tin_Trung_Tam,website chính thức của trung tâm quản trị hệ t...
1,2,tên tiếng anh của trung tâm quản trị hệ thống ...,Thong_Tin_Trung_Tam,tên tiếng anh của trung tâm quản trị hệ thống ...
2,3,tên viết tắt của trung tâm quản trị hệ thống l...,Thong_Tin_Trung_Tam,tên viết tắt của trung tâm quản trị hệ thống l...
3,4,trong quá trình xây dựng và phát triển ban đầu...,Thong_Tin_Trung_Tam,trong quá trình xây dựng và phát triển ban đầu...
4,5,"tháng 8 năm 2019, trung tâm quản trị hệ thống ...",Thong_Tin_Trung_Tam,"tháng 8 năm 2019, trung tâm quản trị hệ thống ..."
...,...,...,...,...
5351,5352,"hội thi tay nghề bộ công thương năm 2014, iuh ...",Thong_Tin_Truong,"hội thi tay nghề bộ công thương năm 2014, đại ..."
5352,5353,hoạt động kỷ niệm ngày quốc tế phụ nữ 8/3/2014,Thong_Tin_Truong,hoạt động kỷ niệm ngày quốc tế phụ nữ 8/3/2014
5353,5354,tiến độ đào tạo năm học 2014-2015 (theo 2 học kỳ),Thong_Tin_Truong,tiến độ đào tạo năm học 2014-2015 (theo 2 học kỳ)
5354,5355,kế hoạch thi tốt nghiệp đợt tháng 07 năm 2014,Thong_Tin_Truong,kế hoạch thi tốt nghiệp đợt tháng 07 năm 2014
5355,5356,danh sách các nhà tài trợ học bổng sinh viên n...,Thong_Tin_Truong,danh sách các nhà tài trợ học bổng sinh viên n...

In [12]:
df1_final.to_csv('data_normalized.csv', index=False, encoding='utf-8-sig')
# df2_final.to_csv('Thong_Tin_Khoa_Normalized.csv', index=False, encoding='utf-8-sig')
# df3_final.to_csv('Thong_Tin_Trung_Tam_Normalized.csv', index=False, encoding='utf-8-sig')
# df4_final.to_csv('Thong_Tin_Truong_Normalized.csv', index=False, encoding='utf-8-sig')
# df5_final.to_csv('Thong_Tin_Tuyen_Sinh_Normalized.csv', index=False, encoding='utf-8-sig')

In [13]:
import pandas as pd
df = pd.read_csv("truong_aug.csv")
score_cols = ["Score_1","Score_2","Score_3","Score_4","Score_5"]
aug_cols = ["Augmented_1","Augmented_2","Augmented_3","Augmented_4","Augmented_5"]

# tìm vị trí score lớn nhất
df["best_idx"] = df[score_cols].values.argmax(axis=1)

# lấy score lớn nhất
df["Best_Score"] = df[score_cols].max(axis=1)

# lấy text tương ứng
df["Best_Augmented"] = [
    df.iloc[i][aug_cols[idx]]
    for i, idx in enumerate(df["best_idx"])
]

# lọc score >= 0.65
df_filtered = df[df["Best_Score"] >= 0.65].copy()

# giữ lại cột cần thiết
df_filtered = df_filtered[[
    "Contents",
    "Labels",
    "Best_Augmented",
    "Best_Score"
]]

print(df_filtered.head())

                                            Contents            Labels  \
0     chúc mừng giáng sinh và chúc mừng năm mới 2026  Thong_Tin_Truong
1  hội cựu chiến binh đại học công nghiệp thành p...  Thong_Tin_Truong
2  biến vảy cá thành giá trị xanh: sinh viên đại ...  Thong_Tin_Truong
3  vượt qua hơn 140 đội thi, sinh viên đại học cô...  Thong_Tin_Truong
4  đại học công nghiệp thành phố hồ chí minh vào ...  Thong_Tin_Truong

                                      Best_Augmented  Best_Score
0  Chào mừng Giáng sinh và chúc bạn một năm mới 2...    0.807063
1  Kỷ niệm 81 năm thành lập quân đội nhân dân Việ...    0.833384
2  Từ vảy cá đến giá trị sinh thái: Sinh viên trư...    0.743086
3  Sinh viên trường Đại học Công nghiệp TP.HCM đã...    0.822520
4  Đại học Công nghiệp TP.HCM đã đạt được thành t...    0.728936

In [14]:
df = df[['Best_Augmented', 'Labels']]

In [16]:
df.to_csv('truong_aug.csv', index=False, encoding='utf-8-sig')